### ISSUE TITLE
example-subpages - "markdown source file not found"

### ISSUE THREAD

**Issue by hkalic** [perak/kitchen-examples#14]
When I do (on Windows in directory _C:\Projects\kitchen>_):
**meteor-kitchen ./example-subpages.json ./example-subpages**
... I get error:
**Error: markdown source file not found "C:\Projects\kitchen\files\lorem_ipsum1.md".**

After I manually copy the **files** directory everything works.

**Comment by perak** [comment]
Did you cloned "example-subpages" into that directory? (or, how you get example-subpages.json there?).

I am curious about your problem - meteor kitchen is not well tested under Windows, so feel free to report any issues, but please post detailed steps how to reproduce error.

Thanks!

**Comment by hkalic** [comment]
I downloaded json file from GitHub - mouse right click on RAW link - Save to... then I started meteor-kitchen ./example-subpages.json ./example-subpages

**Comment by perak** [comment]
Well... it's not enough just to copy json file, you need to clone repository: 
`git clone https://github.com/perak/kitchen-examples.git`

Btw, examples are already installed with meteor-kitchen, and you can run:

`meteor-kitchen --example-subpages ./your_output_directory` without downloading example files.

**Comment by hkalic** [comment]
OK. Thanks for your input and help.
It's been some time and I just now noticed this one Opened so... let's close it.
