### ISSUE TITLE
exemple subpages don`t generate the subpages

### ISSUE THREAD

**Issue by camilamacedo86** [perak/kitchen-examples#17]

**Comment by camilamacedo86** [comment]
The problem is in the second page . Need change the code.

In the RouteController.extend for :


	action: function() {
        if(this.isReady()) { this.render(); } else { this.render("loading"); }
		/*ACTION_FUNCTION*/
	},

**Comment by perak** [comment]
@camilamacedo86 sorry, I think I don't understand whaty's the problem... 

Can you explain your issue with little bit more details please?

Thanks.

**Comment by camilamacedo86** [comment]
Petar,

     When I try use this template don`t show the sub-pages .

     One of the problems I think is in the router of the second page .

     Can you share your codes ? If you do this maybe can I fix the
problems. I really like the idea of this project but you need improve a lot
for have success . I think is impossible developer alone this.

[]s

Camila Macedo

2015-05-18 13:23 GMT-03:00 Petar Korponaić <notifications@github.com>:

**Comment by perak** [comment]
As you can see in live "subpages" example: http://generator-subpages.meteor.com/ , subpages are shown correctly. 

- Did you generated "subpages" example (without modifications) and subpages are not shown?

- If you are trying to add subpages in your custom code, note that subpages are not shown automaticaly: if you want subpages to appear inside parent page you need to set `force_yield_subpages` to `true` inside parent page OR add menu inside parent page with menu items pointing to subpages.

You can see it in "subpages" example: parent page contains menu pointing to subpages. Another approach is in "invoices" example: "invoices.details" page doesn't have menu pointing to subpages but it has `force_yield_subpages` set to true.

If you still think there is a bug in route controller, please help me to reproduce that.

Thanks.

**Comment by camilamacedo86** [comment]
Perak,

   Tks I will check my json file .

[]s

2015-05-18 17:44 GMT-03:00 Petar Korponaić <notifications@github.com>:

**Comment by camilamacedo86** [comment]
Shows outdated.
