### ISSUE TITLE
Human example doesn't work as expected with jumbotron

### ISSUE THREAD

**Issue by jesuslerma** [perak/kitchen-examples#21]
The title attribute doesnt work in the order that appears in the example. I change the order and I put at the last so it works fine for me:

My dear computer,

I want site with three pages: home, customers and about.
In home page I want jumbotron with: text: "Human to describe app, machine to write $
button url: "customers", title: "This application is written in human language!".

Please create one collection: customers.
In customers collection I want three fields: name, address and e-mail.
In customers page I want CRUD for customers collection.
That's it, please create this application for me.
Thank you.
Petar

**Comment by perak** [comment]
@jesuslerma I just tried to build app from example (unchanged) and it works normally. What is your meteor-kitchen version and version of human2machine ?

**Comment by jesuslerma** [comment]
meteor-kitchen 0.9.43 and human2machine 1.4.23. 

I just copy and paste the txt input into my local machine and run the meteor-kitchen command, so the title attribute doesn't work but if I put the url of raw github code it works like the live example. Probably there was a problem with the copy and paste.
