### ISSUE TITLE
application is crashing

### ISSUE THREAD

**Issue by flenoir** [perak/kitchen-examples#25]
hi, 

 i tried to launch the app and i get tis error

=> Errors prevented startup:                  
   
   While processing files with less (for target web.browser):
   client/styles/styles/styles.less:1: Unknown import:
   {}/client/styles/framework/bootstrap3/custom.bootstrap.less

=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

any idea ? 

 regards

 Fabien Lenoir

**Comment by perak** [comment]
Start app again and it will work. This is because file `/client/styles/framework/bootstrap3/custom.bootstrap.less` is auto-generated by `nemo64:bootstrap` on first run, but it happens after meteor detects that included file doesn't exists.

**Comment by flenoir** [comment]
ok so i started again only with a json file

 here's the error

 Creating collection "files"...
Creating collection "gallery"...
Creating stylesheet...
Creating layout...
Creating zone "free_zone"...
Creating component "main_menu"...
Creating page "home"...
Creating component "gallery"...

File not found "/Users/flenoir/Sites/frooster/files/gallery.html".
 
i do not understand ?

 do i need to copy the "files" folder and the 2 gallery files ?

**Comment by perak** [comment]
Path to custom template files (it's your "gallery.html" and "gallery.js") file is relative to json.

**Comment by perak** [comment]
if you have "files" directory in the same place where is your .json, and in that directory you have "gallery.html" and "gallery.json", then your "custom_template" should look like this:

```
"custom_template": "files/gallery"
```

(no leading slash, no extension)

**Comment by perak** [comment]
(btw, meteor-kitchen will properly insert gallery.html and gallery.js content into destination page's html and js files, you don't need to copy anything into destination directory)

**Comment by perak** [comment]
(one more thing - are you using windows? if so, please use backslash as directory separator - meteor-kitchen is "smart" enough to detect and convert slash into backslash, but... never believe program if it is too "smart"  :D )

**Comment by flenoir** [comment]
no i'm on mac

 i keep triyng but still not working

 if i only use the json file, it should create the files directory and the 2 files , right ? but it's not

it's weird

**Comment by flenoir** [comment]
is there a problem with writing rights on this folder ?

**Comment by perak** [comment]
ooops, now I understand your issue: are you trying to build example? You need all files from example directory (not only json)

**Comment by perak** [comment]
I believe you are trying to build `example-upload`, right?

Just clone examples repository.

BTW, all examples are supplied with meteor-kitchen, you can build examples by executing:

`meteor-kitchen --example-upload ./destination_directory`

**Comment by flenoir** [comment]
thanks it's working now
 ;)

**Comment by perak** [comment]
:+1:
