### ISSUE TITLE
IDE example: can access other peoples files.

### ISSUE THREAD

**Issue by whatsdis** [perak/kitchen-examples#26]
I can access other peoples files as well, actually able to view everyone's project ever created.

**Comment by perak** [comment]
@whatsdis How/where you can see other people's files? 

Other people's files are not published at all. Here is how `server/publish/file_system.js` looks like:
```
Meteor.publish("project_files", function(projectId) {
	return FileSystem.find({projectId:projectId,createdBy:this.userId}, {sort:["filename"]});
});

Meteor.publish("file", function(fileId) {
	return FileSystem.find({_id:fileId,createdBy:this.userId}, {});
});
```

Humm.... are you sure meteor-kitchen properly removed "autopublish" and "insecure" packages from your project? (that's first thing meteor-kitchen executes after creating new project:

`meteor remove insecure autopublish`

If that's not executed (you can check do you still have those packages in your `.meteor/packages` file), let's see why.

What version of **meteor** & what version of **meteor-kitchen** are you using? `meteor --version`, `meteor-kitchen --version` and which OS?

**Comment by whatsdis** [comment]
ah okay, I did not remove those!. thank you. I'm using the windows latest meteor version on win 7.

**Comment by perak** [comment]
@whatsdis Those should be remove automatically. So, if kitchen doesn't remove automatically then this is still an issue.

?

**Comment by whatsdis** [comment]
giving it a shot!

**Comment by whatsdis** [comment]
that did it! now shows only my files.
