### ISSUE TITLE
ide example: information about admin view is missing

### ISSUE THREAD

**Issue by whatsdis** [perak/kitchen-examples#27]
there's a route for /admin but I'm not sure what the default username and password is or there's something I missed to access the admin panel?

**Comment by perak** [comment]
@whatsdis See readme.md you need to make yourself admin from mongo shell.

**Comment by whatsdis** [comment]
thank you.

**Comment by perak** [comment]
https://github.com/perak/kitchen-examples/tree/master/example-admin

**Comment by whatsdis** [comment]
thanks @perak!

**Comment by whatsdis** [comment]
btw how do you access mongo shell? what is the default credentials?
