### ISSUE TITLE
Field "time" doesn't work

### ISSUE THREAD

**Issue by dearamy** [perak/kitchen-examples#35]
Hi Perak
It's me again, thank you for your patient and your amazing kitchen!
Somehow I can't use the time field in the data-view example 

The json file seems quite right
`{
	"name": "time",
	"title": "Time",
	"type": "time",
	"default": "now",
	"required": true,
	"format": "hh:mm",
	"searchable": true,
	"sortable": true,
	"exportable": true,
	"input": "text",
	"show_in_dataview": true,
	"show_in_insert_form": true,
	"show_in_update_form": true,
	"show_in_read_only_form": true,
},`

And the "add new" shows the default time right too.
But for some reason it doesn't produce any template events in the .js file and my browser give me an error "Exception in template helper: TypeError: s.toUpperCase is not a function" every time I insert a data with time.

**Comment by perak** [comment]
@dearamy are you using latest meteor-kitchen v0.9.61?

**Comment by dearamy** [comment]
I'm using Meteor Kitchen v0.9.57 on Windows 10, it seems like the latest version for windows

**Comment by dearamy** [comment]
I was wrong, I just download the 0.9.61 meteor-kitchen and it works well

**Comment by perak** [comment]
Great, so.. closing this issue?
