### ISSUE TITLE
Error on calculating checksum when building with options

### ISSUE THREAD

**Issue by rikyperdana** [perak/kitchen-examples#44]
`Calculating checksums...

Error calculating file checksum. No such file or directory
`

It generates error each time I build a project with CoffeeScript or Jade options
Yet the project generated perfectly :)

**Comment by perak** [comment]
@rikyperdana thanks for bug-catch. Fixed and will be available in next version: `0.9.70`

**Comment by perak** [comment]
@rikyperdana I think this bug is fixed in `v0.9.70`. Can I close this issue?

**Comment by rikyperdana** [comment]
Sure pal :)
