### ISSUE TITLE
changing the default query name breaks the page

### ISSUE THREAD

**Issue by rikyperdana** [perak/kitchen-examples#45]
`queries:
        - name: current_user_data`
works well

But when i change it to
`queries:
        - name: another_name`
The spinner keep spinning.
But when i check it with meteortoys, the query subscribed well
Is current user data query restricted to this "current_user_data" name?

--Edit--
i also found out that it also happens to query name "admin_users" and "admin-user"

**Comment by perak** [comment]
@rikyperdana yes, "current_user_data" is defined in "perak:user_roles" package. Spinner keeps spinning because you don't have publication "another_name". You can create one. If you are using CLI, you can create one .js file and reference it in the input file in "copy_files" array, like this:

```json
"application" : {
...
  "copy_files": [
    { "source": "path_to_your_file_relative_to_this_input_json_file.js", "dest": "SERVER_PUBLISH_DIR/" }
  ]
}
```

**Comment by rikyperdana** [comment]
I'm a CLI lover but I also admire your GUI Kitchen. Thanks a lot for the answer :)
