### ISSUE TITLE
Filters with regex like expressions cause kitchen parse error

### ISSUE THREAD

**Issue by anthonymanzo** [perak/kitchen-examples#48]
Hi,
I have a filter I want to use :
`"filter": "{\"distinguishedname\": { \"$not\":/.*DISABLED.*/}}",`
But I get the following parse error - 
Error parsing query "adusers" filter string. Error parsing JSON
When I put quotes around the expression, it doesn't fail, but it also isn't correct syntax and the fitler just doesn't work.
What to do?
Thanks kindly.
Tony

**Comment by perak** [comment]
@anthonymanzo try this:

```json
"filter": "{\"distinguishedname\": { \"$not\": \"new RegExp(/.*DISABLED.*/)\"}}"
```

**Comment by anthonymanzo** [comment]
That works great.  Thank you.
You can close this one!

On Dec 6, 2016, at 12:52 PM, Petar Korponaić <notifications@github.com<mailto:notifications@github.com>> wrote:


@anthonymanzo<https://github.com/anthonymanzo> try this:

"filter": "{\"distinguishedname\": { \"$not\": \"new RegExp(/.*DISABLED.*/)\"}}"

**Comment by perak** [comment]
Great 👍
