### ISSUE TITLE
Manual HTML and JS editor not working

### ISSUE THREAD

**Issue by deviousjack** [perak/kitchen-examples#56]
Hi Petar,
When I add custom component then try to edit the JS and HTML on the component it won't work.
Thanks

**Comment by perak** [comment]
You need to turn visual designer off (See "Turn designer off" button in this screenshot: 
<img width="1440" alt="screen shot 2017-06-27 at 11 13 54 pm" src="https://user-images.githubusercontent.com/5630814/27610389-6b4e6af4-5b8e-11e7-9f5c-6bdd2b09f0de.png"> )

**Comment by deviousjack** [comment]
Thanks so much petar it works.
