### ISSUE TITLE
Multiple queries named "employee_list" with different properties

### ISSUE THREAD

**Issue by MercedesAMG1** [perak/kitchen-examples#6]
Error I get is above on my localhost terminal
I added a new collection(employees) to the invoices example and followed along with the customers setup and I am using the GUI

customers
  query .... Your Name & Collection name are BLANK
    components  (1)
      view
        query .... you have Name is customer_list and collection is customers

On the GUI - under my setup 

employees
  query .... My Name & Collection name are BLANK but I can't save it cause GUI says these cannot  be blank
    components  (1)
      view
        query .... I have Name is employee_list and collection is employees

And of course this is where the error comes from because if I name the first query employee_list then I have 2 "employee_list" query entries. I tried changing the other one but it needs to be employee_list

So I cant setup the view based on your example
Don't know what to do

**Comment by perak** [comment]
Hi,

You cannot have two queries with different properties in the same app - actually, query is publication name used for publish/subscribe mechanism.

So, if two queries are named "employee_list", all their properties need to be the same - not only "name", and "collection" - "filter" and "options" must be the same too. 

If you need two different, why you just not rename one of them?

Also, feel free to paste some example code here?

**Comment by MercedesAMG1** [comment]
That is not the problem

Somehow I got 2 with the same name now when trying to rename either one "kitchen" won't allow me to save with no name and no collection

Yet

Customers has a pages/view top level query with no name and no collection. A lower level query establishes the publication

The issue is with having saved a top level query under view, then realizing it shouldn't be there, then trying to correct, delete or rename that change "kitchen" will NOT let me

**Comment by perak** [comment]
Aha... are you using kitchen-GUI or you are writing directly json file in editor? 

If you are using kitchen-GUI (it's full of bugs) you can solve this by switching view: View -> Source (json) and remove that in editor.

Please let me know did it helps.

**Comment by MercedesAMG1** [comment]
No problem. I was using the GUI and have since backed off because of (buggy)
But I will use the json
