### ISSUE TITLE
type crud field

### ISSUE THREAD

**Issue by xiao17** [perak/kitchen-examples#9]
Hi!  I use crud field like this:

{
	"name": "menu",
	"title": "some food"
	"type": "array",
	"array_item_type": "object",
	"input":"crud",
	"crudfields":[
		{ "name": "name", "title": "name", "required": true, "exportable": true, "input": "text" },
		{ "name": "price", "title": "price", "required": true, "exportable": true, "input":"text" },
		{ "name": "date", "title": "time", "type": "date", "required": true, "exportable": true, "input":"datepicker" },
		{ "name": "count", "title": "amount", "type": "integer", "required": true, "exportable": true, "input":"text" }
	],
	"exportable": true,
	"crudinsert_title": "insertTitle"
}

But in my insert form page, I can't find any fields in crud modal dialog,  just display the submit and cancel buttons.

**Comment by perak** [comment]
Hi,

Sorry, that's bug in documentation. Correct is `crud_fields` not `crudfields`:

```
{
  "name": "menu",
  "title": "some food"
  "type": "array",
  "array_item_type": "object",
  "input":"crud",
  "crud_fields":[
    { "name": "name", "title": "name", "required": true, "exportable": true, "input": "text" },
    { "name": "price", "title": "price", "required": true, "exportable": true, "input":"text" },
    { "name": "date", "title": "time", "type": "date", "required": true, "exportable": true, "input":"datepicker"},
    { "name": "count", "title": "amount", "type": "integer", "required": true, "exportable": true, "input":"text" }
  ],
  "exportable": true,
  "crudinsert_title": "insertTitle"
}
```

**Comment by perak** [comment]
(and also `crud_insert_title` instead `crudinsert_title`)

**Comment by perak** [comment]
I just fixed and uploaded new documentation. Thank you for bug report. Enjoy! :)

**Comment by xiao17** [comment]
Thank you very much, It works!
